variables:
  buildConfiguration: 'Release'

jobs:
- job: BuildAndRunCodeAnalysis
  displayName: Build and run code analysis
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution with code analysis
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: -c $(buildConfiguration) -warnaserror

- job: RunTestsOnWindows
  displayName: Run tests on Windows
  pool:
    vmImage: windows-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: -c $(buildConfiguration) -p:RunCodeAnalysis=false
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 30
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build

- job: RunTestsOnLinux
  displayName: Run tests on Linux
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: -c $(buildConfiguration) -p:RunCodeAnalysis=false
  - script: sudo npm install -g html-validate
    displayName: Install html-validate NPM package
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 30
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build

- job: RunTestsOnMacOS
  displayName: Run tests on MacOS
  pool:
    vmImage: macOS-latest
  steps:
  - task: DotNetCoreCLI@2
    displayName: Build solution
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: -c $(buildConfiguration) -p:RunCodeAnalysis=false
  - task: DotNetCoreCLI@2
    displayName: Run tests
    timeoutInMinutes: 30
    inputs:
      command: test
      projects: '**/*Tests.csproj'
      arguments: -c $(buildConfiguration) -s "azure-pipelines.runsettings" --no-build